### PR TITLE
update to 3.2.1

### PR DESCRIPTION
**Pull request by oliveregger**
updated org packages
fix proxy issue
@qligier matchbox-server tests are not running anymore locally when removing @Ignore annotation

### CODE REVIEW

**Comment by qligier** [comment]
I will check that.

Edit: It looks like Jetty is missing:
```
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/thread/AutoLock
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.jndi.ContextFactory
```
Edit2: a few issues caused by upgraded dependencies

**Comment by qligier** [comment]
I have pushed a commit that upgrades the Jetty dependency to make Matchbox bootable again.
Now, Jetty depends on Slf4j 2 and Spring on Slf4j 1, I have excluded Slf4j 2 and logs are back again (excluding Slf4j 1 made Spring crash).

**Comment by qligier** [comment]
Two tests to fix:

`CdaTransformTests` fails with:
```
ERROR ca.uhn.fhir.context.ModelScanner [ModelScanner.java:565] HAPI-1727: Unknown class[org.hl7.fhir.r5.model.MedicationUsage] for resource definition: MedicationUsage
ERROR ca.uhn.fhir.context.ModelScanner [ModelScanner.java:565] HAPI-1727: Unknown class[org.hl7.fhir.r5.model.DocumentManifest] for resource definition: DocumentManifest
ERROR org.quartz.core.JobRunShell [JobRunShell.java:211] Job HAPI.ch.ahdis.matchbox.MatchboxJpaConfig$$EnhancerBySpringCGLIB$$359f23c4 threw an unhandled Exception: 
ca.uhn.fhir.context.ConfigurationException: HAPI-1725: Unknown class[org.hl7.fhir.r5.model.Population] for data type definition: Population
Caused by: java.lang.ClassNotFoundException: org.hl7.fhir.r5.model.Population
```
A R4/R5 confusion, it seems.

`IgValidateR4Test` fails with:
```
2023-04-04 14:25:17.941 [main] ERROR c.a.v.IgValidateR4TestStandalone [IgValidateR4TestStandalone.java:206] error loading R4 or ImplementationGuide
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HAPI-1758: Unable to find classpath resource: /ch.fhir.ig.ch-emed#3.0.0.tgz
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "resources" is null
```
The resource is not found in the classpath, let's add the profile package to the resources for now.

**Comment by oliveregger** [comment]
> A R4/R5 confusion, it seems.

R5 hapi-fhir and R5 core package confusion ... see #95

**Comment by oliveregger** [comment]
i can run the tests locally, however with mvn test from matchbox they are not yet run, is that intentionally?
(only matchbox-server tests are not run, tests in matchbox-engine are run).

mvn clean test 

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]

**Comment by qligier** [comment]
Matchbox is configured with JUnit 5, but the server still uses JUnit 4 annotations, that is why Maven won't execute them. There is a comment saying CanonicalizerTests only run with JUnit 4, it seems the upgrade requires a bit of work.
I've temporarily fixed that by forcing JUnit 4 in the server.

I have still the issue "Validation for profile http://fhir.ch/ig/ch-emed/StructureDefinition/XXX not supported by this server, but additional ig's could be configured" when running the tests with Maven, but not with Intellij.

Edit: GitHub's runner does not encounter this error, so it really seems a timing issue.

I've also changed the port used by the server in each test because even running them sequentially threw "port already in use" errors. Now, they can be run in parallel.

**Pull request merged**
