### PR TITLE
validation gui error when clicking copy validation url feature request

### LINKED ISSUE #296: Validation GUI: Error when clicking & copy validation url feature request
1. when clicking in the GUI a validation error appears
2. Would it be possible to have a "copy url"  button to the right in actions, that a GET $validae request is constructed which we could you reuse and share?

image

image

### PR DESCRIPTION
**Pull request by qligier**
Fixes #296

### CODE REVIEW

**Comment by qligier** [comment]
Setting the `server.max-http-request-header-size` is an unfortunate side effect of that URL strategy. It's useless to send the document content in the first request (for the HTML page), but we can't use the URL anchor for that because it's used by Angular for navigation.
Changing that would require some work.

**Review by oliveregger — CHANGES_REQUESTED** [review]
I have still a small timing? issue when i do this validation in an development instance:

```http
http://localhost:8080/matchbox/?resource=ewogICAgICAgICAgICAgICAgInJlc291cmNlVHlwZSI6ICJEb2N1bWVudFJlZmVyZW5jZSIsCiAgICAgICAgICAgICAgICAiY29udGFpbmVkIjogWwogICAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgICAgInJlc291cmNlVHlwZSI6ICJQYXRpZW50IiwKICAgICAgICAgICAgICAgICAgICAgICAgImlkIjogIjEiLAogICAgICAgICAgICAgICAgICAgICAgICAiaWRlbnRpZmllciI6IFsKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidXNlIjogInVzdWFsIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImNvZGluZyI6IFsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAic3lzdGVtIjogImh0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL0NvZGVTeXN0ZW0vdjItMDIwMyIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImNvZGUiOiAiTVIiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJzeXN0ZW0iOiAidXJuOm9pZDoyLjE2Ljc1Ni44ODg4ODguMy4xIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidmFsdWUiOiAiODczNCIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAiZXh0ZW5zaW9uIjogWwogICAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgICAgInVybCI6ICJodHRwOi8vZmhpci5jaC9pZy9jaC1lcHItZmhpci9TdHJ1Y3R1cmVEZWZpbml0aW9uL2NoLWV4dC1kZWxldGlvbnN0YXR1cyIsCiAgICAgICAgICAgICAgICAgICAgICAgICJ2YWx1ZUNvZGluZyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJzeXN0ZW0iOiAidXJuOm9pZDoyLjE2Ljc1Ni41LjMwLjEuMTI3LjMuMTAuMTgiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImNvZGUiOiAidXJuOmUtaGVhbHRoLXN1aXNzZToyMDE5OmRlbGV0aW9uU3RhdHVzOmRlbGV0aW9uTm90UmVxdWVzdGVkIgogICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAgICJ1cmwiOiAiaHR0cDovL2ZoaXIuY2gvaWcvY2gtZXByLWZoaXIvU3RydWN0dXJlRGVmaW5pdGlvbi9jaC1leHQtYXV0aG9yLWF1dGhvcnJvbGUiLAogICAgICAgICAgICAgICAgICAgICAgICAidmFsdWVDb2RpbmciOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAic3lzdGVtIjogInVybjpvaWQ6Mi4xNi43NTYuNS4zMC4xLjEyNy4zLjEwLjYiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImNvZGUiOiAiSENQIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkaXNwbGF5IjogIkhlYWx0aGNhcmUgcHJvZmVzc2lvbmFsIgogICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgICJtYXN0ZXJJZGVudGlmaWVyIjogewogICAgICAgICAgICAgICAgICAgICJzeXN0ZW0iOiAidXJuOmlldGY6cmZjOjM5ODYiLAogICAgICAgICAgICAgICAgICAgICJ2YWx1ZSI6ICJ1cm46b2lkOjEuMy42LjEuNC4xLjEyNTU5LjExLjEzLjIuMS4yOTUxIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJzdGF0dXMiOiAiY3VycmVudCIsCiAgICAgICAgICAgICAgICAidHlwZSI6IHsKICAgICAgICAgICAgICAgICAgICAiY29kaW5nIjogWwogICAgICAgICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAic3lzdGVtIjogImh0dHA6Ly9zbm9tZWQuaW5mby9zY3QiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImNvZGUiOiAiNzIxOTEyMDA5IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkaXNwbGF5IjogIk1lZGljYXRpb24gc3VtbWFyeSBkb2N1bWVudCAocmVjb3JkIGFydGlmYWN0KSIKICAgICAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgIF0KICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY2F0ZWdvcnkiOiBbCiAgICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAgICAiY29kaW5nIjogWwogICAgICAgICAgICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJzeXN0ZW0iOiAiaHR0cDovL3Nub21lZC5pbmZvL3NjdCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImNvZGUiOiAiNDIyNzM1MDA2IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZGlzcGxheSI6ICJTdW1tYXJ5IGNsaW5pY2FsIGRvY3VtZW50IChyZWNvcmQgYXJ0aWZhY3QpIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgICJzdWJqZWN0IjogewogICAgICAgICAgICAgICAgICAgICJyZWZlcmVuY2UiOiAiaHR0cDovL2V4YW1wbGUub3JnL1BhdGllbnQvRnJhbnpNdXN0ZXJOZWVkc0Fic29sdXRlVXJsIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJkYXRlIjogIjIwMjAtMDYtMjlUMTE6NTg6MDArMDA6MDAiLAogICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIjItNy1NZWRpY2F0aW9uQ2FyZCIsCiAgICAgICAgICAgICAgICAic2VjdXJpdHlMYWJlbCI6IFsKICAgICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAgICJjb2RpbmciOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInN5c3RlbSI6ICJodHRwOi8vc25vbWVkLmluZm8vc2N0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiY29kZSI6ICIxNzYyMTAwNSIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImRpc3BsYXkiOiAiTm9ybWFsIChxdWFsaWZpZXIgdmFsdWUpIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgICJjb250ZW50IjogWwogICAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgICAgImF0dGFjaG1lbnQiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAiY29udGVudFR5cGUiOiAidGV4dC94bWwiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImxhbmd1YWdlIjogImRlLUNIIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ1cmwiOiAidXJuOnV1aWQ6ZDhkMWZlNDQtMDdlOS00YTg0LTk4NWYtZmRlOTdkNzdkNTRiIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJjcmVhdGlvbiI6ICIyMDIwLTA2LTI5VDExOjU4OjAwKzAwOjAwIgogICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgICAiZm9ybWF0IjogewogICAgICAgICAgICAgICAgICAgICAgICAgICAgInN5c3RlbSI6ICJodHRwOi8vaWhlLm5ldC9maGlyL2loZS5mb3JtYXRjb2RlLmZoaXIvQ29kZVN5c3RlbS9mb3JtYXRjb2RlIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJjb2RlIjogInVybjppaGU6cGhhcm06cG1sOjIwMTMiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImRpc3BsYXkiOiAiUGhhcm1hY3kgUE1MIgogICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgICJjb250ZXh0IjogewogICAgICAgICAgICAgICAgICAgICJmYWNpbGl0eVR5cGUiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJjb2RpbmciOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInN5c3RlbSI6ICJodHRwOi8vc25vbWVkLmluZm8vc2N0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiY29kZSI6ICIyNjQzNTgwMDkiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkaXNwbGF5IjogIkdlbmVyYWwgcHJhY3RpY2UgcHJlbWlzZXMgKGVudmlyb25tZW50KSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgInByYWN0aWNlU2V0dGluZyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImNvZGluZyI6IFsKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAic3lzdGVtIjogImh0dHA6Ly9zbm9tZWQuaW5mby9zY3QiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJjb2RlIjogIjM5NDgwMjAwMSIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImRpc3BsYXkiOiAiR2VuZXJhbCBtZWRpY2luZSAocXVhbGlmaWVyIHZhbHVlKSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgInNvdXJjZVBhdGllbnRJbmZvIjogewogICAgICAgICAgICAgICAgICAgICAgICAicmVmZXJlbmNlIjogIiMxIgogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfQ%3D%3D&profile=http%3A%2F%2Fhl7.org%2Ffhir%2FStructureDefinition%2FDocumentReference#/validate
```
returns a red error message box

The profile 'http://hl7.org/fhir/StructureDefinition/DocumentReference' is unknown to this server

**Comment by qligier** [comment]
Probably because R4 is not loaded as IG.

**Comment by oliveregger** [comment]
> Probably because R4 is not loaded as IG.

no it is loaded, it does also do the validation, but it shows the error, thats why I think it's a timing issue ( i copied that link out of the gui)

**Comment by qligier** [comment]
I don't think so, it waits for the data loading until it checks for the validation request:
https://github.com/ahdis/matchbox/blob/7d4e4b1d2ff271146a1768f44a962e3a1f16a6cd/matchbox-frontend/src/app/validate/validate.component.ts#L78-L91

If you check the calls to http://localhost:8080/matchboxv3/fhir/OperationDefinition/-s-validate and http://localhost:8080/matchboxv3/fhir/ImplementationGuide?_count=1000&_sort=title, you should see that no profile nor IG is returned, even though at least FHIR Core is loaded.
That seems to be an issue in the Java code. I think it only happens when you start Matchbox without anything in `hapi.fhir.implementationguides`.

**Comment by oliveregger** [comment]
@qligier thanks, you are right!

**Comment by oliveregger** [comment]
has been merged directly with https://github.com/ahdis/matchbox/commit/1ffc0369497d6b2fb2778fa01e9fa6552d31a076

**Comment by qligier** [comment]
It's an edge case, not sure if we want to fix it.
We would need to add code to make sure the core, terminology and extensions IGs are implicitly loaded if they are not explicitly added to the configuration (because the validator will load them anyway).

**Pull request merged**
