### PR TITLE
Upgrade to fhir core 6.4.0

### PR DESCRIPTION
**Pull request by qligier**

### CODE REVIEW

**Comment by qligier** [comment]
Integration tests are passing, failures are unrelated.
Also, we have a nice JUnit summary now for unit and integration tests: https://github.com/ahdis/matchbox/actions/runs/11804133574?pr=310

**Review by oliveregger — APPROVED** [review]
looks good, however we should sync our tab / spaces approach, it looks difficult if there are so many changes and a lot of changes are only whitespace in the pr. especially the ones from hapi-fhir project, because if we want to provide a pr back, we need to have the same space/tab behaviour as they have.

@qligier could you adpat that? and then we could release tomorrow if that is ok.

**Comment by oliveregger** [comment]
6.4.1 has just been published, should we update to that?

**Comment by qligier** [comment]
Yes, I'll upgrade to 6.4.1 instead, and fix the indentation issue: my editor is respecting our editorconfig (tabs, 3 spaces) instead of keeping the original one (spaces, 2 spaces)

**Comment by qligier** [comment]
Upgraded to 6.4.1, with a nice diff!

**Review by oliveregger — APPROVED** [review]

**Pull request merged**
